// src/components/Footer.tsx
import { component$ } from "@builder.io/qwik";
import { Link } from "@builder.io/qwik-city";
import Logo from "~/assets/logo.svg?jsx";
import type { NavItem } from "./Navbar";
import { navItems, navServices } from "./Navbar";
import { IoMailSolid, IoLocationSharp } from "@qwikest/icons/ionicons";


export default component$(() => {

  return (
    <footer class="flex flex-col">
      <div class="mx-auto max-w-6xl w-full flex flex-col md:flex-row gap-3 md:gap-8 justify-between items-center md:items-start border-t border-slate-100/20">

        <div class="flex flex-col gap-3 text-center md:text-left items-center md:items-start w-full py-4">
          <div class="h-12 w-12">
            <Logo />
          </div>
          <h3 class="text-lg font-bold tracking-wider text-yellow-300">Webundance</h3>
          <p class="w-[80%] md:w-full text-slate-400">Indianapolis website and copywriting services for small to medium-sized businesses.</p>
        </div>

        <div class="text-center md:text-left w-full border-t md:border-none border-slate-100/20 py-3 md:pl-16">
          <h3 class="font-bold mb-3 text-lg">Browse</h3>
          <ul class="flex flex-row md:flex-col justify-evenly">
            {navItems.map((item: NavItem, index) => (
              item.name.toLowerCase() !== "services" ? (
                <li key={index}>
                  <Link href={item.link} class="text-slate-400 hover:text-slate-100 inline-flex flex-col py-3 md:py-2 w-full md:w-fit">{item.name}</Link>
                </li>
              ) : null
            ))}
          </ul>
        </div>

        <div class="text-center md:text-left w-full border-t md:border-none border-slate-100/20 py-3">
          <h3 class="font-bold mb-3 text-lg"><Link href="/#our-services">Services</Link></h3>
          <ul class="flex flex-col">
            {navServices.map((item: NavItem, index) => (
              item.name.toLowerCase() !== "services" ? (
                <li key={index}>
                  <Link href={item.link} class="text-slate-400 hover:text-slate-100 inline-flex flex-col py-3 md:py-2 w-full md:w-fit">{item.name}</Link>
                </li>
              ) : null
            ))}
          </ul>
        </div>

        <div class="text-center md:text-left w-full border-t md:border-none border-slate-100/20 py-3">
          <h3 class="font-bold mb-3 text-lg"><Link href="/contact">Contact</Link></h3>
          <ul class="flex flex-col items-center md:items-start">
            <li>
              <a href="mailto:contact@webundance.com" class="text-slate-400 hover:text-slate-100 inline-flex flex-row gap-2 py-3 md:py-2 w-full md:w-fit items-center"><IoMailSolid /> contact@webundance.com</a>
            </li>
            <li>
              <span class="text-slate-400 hover:text-slate-100 inline-flex flex-row gap-2 py-3 md:py-2 w-full md:w-fit items-center"><IoLocationSharp /> Indianapolis, Indiana</span>
            </li>
          </ul>
        </div>
      </div>

      <div class="bg-blue-200/10 py-3 border-t border-slate-100/20">
        <div class="mx-auto max-w-6xl flex flex-col md:flex-row justify-between items-center gap-4">
          <p>&copy; 2024 Webundance. All Rights Reserved.</p>
          <div><Link href="/">Privacy Policy</Link></div>
        </div>
      </div>
    </footer>
  );
});

// components/footer.vue
<script setup lang="ts">
const currentYear = new Date().getFullYear();
</script>

<template>
	<footer class="bg-neutral-900 text-neutral-400 pt-16 pb-8">
		<div class="container px-3 md:px-0 mx-auto max-w-5xl">
			<div class="grid grid-cols-2 md:grid-cols-4 gap-y-8">
				<!-- Logo -->
				<div class="col-span-2">
					<NuxtLink to="/" class="flex gap-2 items-center w-fit">
						<img src="/favicon.ico" class="size-10">
						<h3 class="text-primary-400 font-bold text-xl">
							Webundance
						</h3>
					</NuxtLink>
					<p class="max-w-xs">
						Custom websites and AI automation solutions for local Indiana businesses. Save time, look professional, and grow your business.
					</p>
				</div>

				<!-- Service Links -->
				<div>
					<h3 class="font-semibold text-neutral-50 mb-4">
						Services
					</h3>
					<ul class="space-y-3">
						<li>
							<NuxtLink to="/automation" class="hover:text-neutral-50 transition-colors">
								Admin Automation
							</NuxtLink>
						</li>
						<li>
							<NuxtLink to="/website-upgrade" class="hover:text-neutral-50 transition-colors">
								Website Upgrade
							</NuxtLink>
						</li>
					</ul>
				</div>

				<!-- Company Links -->
				<div>
					<h3 class="font-semibold text-neutral-50 mb-4">
						Company
					</h3>
					<ul class="space-y-3">
						<li>
							<NuxtLink to="/about" class="hover:text-neutral-50 transition-colors">
								About
							</NuxtLink>
						</li>
						<li>
							<NuxtLink to="/contact" class="hover:text-neutral-50 transition-colors">
								Contact
							</NuxtLink>
						</li>
						<li>
							<NuxtLink to="/book-call" class="hover:text-neutral-50 transition-colors">
								Book a Call
							</NuxtLink>
						</li>
					</ul>
				</div>

				<div class="border-t border-neutral-500 mt-8 pt-8 text-sm flex flex-col md:flex-row justify-between col-span-full">
					<p>&copy; {{ currentYear }} Webundance. All rights reserved.</p>
					<div class="mt-4 md:mt-0">
						<NuxtLink to="/privacy" class="hover:text-neutral-50 mr-6">
							Privacy Policy
						</NuxtLink>
						<NuxtLink to="/terms" class="hover:text-neutral-50">
							Terms of Service
						</NuxtLink>
					</div>
				</div>
			</div>
		</div>
	</footer>
</template>
