// components/nav-bar.vue
<script setup lang="ts">
const menuOpen = ref(false);

const navLinks = [
	{
		id: 1,
		label: "Home",
		href: "/",
	},
	{
		id: 2,
		label: "About",
		href: "/about",
	},
	{
		id: 3,
		label: "Website Upgrade",
		href: "#",
	},
	{
		id: 4,
		label: "Automation",
		href: "#",
	},
];
</script>

<template>
	<nav class="sticky top-0 z-20 border-neutral-200 backdrop-blur-sm bg-white">
		<div class="flex justify-between items-center p-4 mx-auto w-full max-w-5xl">
			<!-- Logo -->
			<NuxtLink to="/" class="flex gap-2 items-center cursor-pointer">
				<img src="/favicon.ico" alt="logo" class="size-12">
				<h1 class="text-xl font-bold text-primary">
					Webundance
				</h1>
			</NuxtLink>

			<!-- Nav Links -->
			<div class="flex gap-6 items-center max-sm:hidden">
				<div v-for="navLink in navLinks" :key="navLink.id">
					<NuxtLink :to="navLink.href" class="cursor-pointer transition-colors ease-in-out hover:text-primary">
						{{ navLink.label }}
					</NuxtLink>
				</div>
				<UButton to="/contact" class="text-base" size="lg">
					Get Started
				</UButton>
			</div>

			<button class="md:hidden" @click="() => (menuOpen = !menuOpen)">
				<div v-if="menuOpen" class="flex items-center">
					<UIcon name="i-lucide-x" size="xl" class="size-7" />
				</div>
				<div v-else class="flex items-center">
					<UIcon name="i-lucide-menu" size="xl" class="size-7" />
				</div>
			</button>
		</div>

		<!-- Mobile Menu -->
		<Transition name="expand">
			<div v-if="menuOpen" class="overflow-hidden md:hidden p-4 mb-4 border-b border-neutral-300">
				<div class="flex flex-col gap-4 text-lg">
					<div v-for="navLink in navLinks" :key="navLink.id">
						<NuxtLink
							:to="navLink.href"
							class="px-2 py-2 hover:text-primary transition-colors ease-in-out"
							@click="() => (menuOpen = false)"
						>
							{{ navLink.label }}
						</NuxtLink>
					</div>

					<UButton
						size="lg"
						class="text-base justify-center"
						@click="() => { menuOpen = false; navigateTo('/contact'); }"
					>
						Get Started
					</UButton>
					<UButton
						size="lg"
						variant="outline"
						class="text-base justify-center"
						@click="() => { menuOpen = false; navigateTo('/book-call'); }"
					>
						Book a Call
					</UButton>
				</div>
			</div>
		</Transition>
	</nav>
</template>

<style scoped>
.expand-enter-active,
.expand-leave-active {
	transition: all 0.2s ease-out;
	max-height: 300px; /* Adjust this value based on your content height */
}

.expand-enter-from,
.expand-leave-to {
	max-height: 0;
	opacity: 0;
}

.expand-enter-to,
.expand-leave-from {
	max-height: 300px;
	opacity: 1;
}
</style>

// src/components/NavBar.tsx
import { component$, useSignal, $ } from "@builder.io/qwik";
import { Link } from "@builder.io/qwik-city";
import { IoMenuSharp, IoCloseSharp } from "@qwikest/icons/ionicons";
import Logo from "./Logo";

interface NavItem {
  name: string;
  link: string;
}

export default component$(() => {

  const navItems: NavItem[] = [
    { name: "Home", link: "/" },
    { name: "About", link: "/about" },
    { name: "Services", link: "/services" },
    { name: "Portfolio", link: "/portfolio" },
  ];

  const menuIsOpen = useSignal(false);
  const menuLeft = useSignal("left-[-100%]");

  const toggleMenu = $(() => {
    menuIsOpen.value = !menuIsOpen.value;

    if (menuIsOpen.value == true) {
      menuLeft.value = "left-0";
    } else {
      menuLeft.value = "left-[-100%]";
    }
  });


  return (
    <nav class="p-4 md:p-6 mx-auto max-w-6xl flex flex-row justify-between font-medium text-white items-center">
      <div class="w-16 h-16">
        <Link href="/"><Logo /> </Link>
      </div>
      <div class={`md:static absolute md:min-h-fit min-h-[70vh] transition-[left] ${menuLeft.value} md:w-auto w-full flex items-center px-5 top-[12%] bg-slate-800 md:bg-transparent`}>
        <ul class="flex md:flex-row flex-col md:items-center md:gap-[4vw] gap-16 text-xl md:text-base">
          {navItems.map((item, index) => (
            <li key={index}>
              <Link href={item.link} class="hover:text-gray-300 py-4">{item.name}</Link>
            </li>
          ))}
        </ul>
      </div>
      <div class="flex items-center gap-6">
        <button class="focus:ring-offset-3 relative inline-flex h-fit w-fit rounded-full border border-blue-100/20 bg-blue-200/10 px-4 py-2 text-blue-200 outline-none ring-yellow-300 transition-colors after:absolute after:inset-0 after:-z-10 after:animate-pulse after:rounded-full after:bg-yellow-100 after:bg-opacity-0 after:blur-md after:transition-all after:duration-500 hover:border-yellow-200/40 hover:text-yellow-300 after:hover:bg-opacity-15 focus:ring-2">Contact</button>
        <div class="text-3xl cursor-pointer md:hidden" onClick$={toggleMenu}>{menuIsOpen.value ? <IoCloseSharp /> : <IoMenuSharp />} </div>
      </div>
    </nav>
  );
});
